### ISSUE TITLE
es-0.9.2 don't build on Linux/Debian/Trixie x86-64 (getenv declaration)

### ISSUE THREAD

**Issue by bstarynk** [wryun/es-shell#169]
after 

     './configure'  '--with-readline' '--prefix=/usr/local' 'CC=/usr/bin/gcc-14' 'CFLAGS=-O2 -g2' 

the build with GNU make (4.4.1, the system one) fails with

```
src/Shell/Es-0.9.2 9:19 % make
/usr/bin/gcc-14  -I. -I. -W -Wall -Wno-implicit-fallthrough -Wno-cast-function-type -Wno-missing-field-initializers -Wno-unused-parameter -Wno-clobbered -O2 -g2   -c -o input.o input.c
input.c:282:1: error: conflicting types for ‘getenv’; have ‘char *(char *)’
  282 | getenv(char *name)
      | ^~~~~~
In file included from stdenv.h:94,
                 from es.h:4,
                 from input.c:4:
/usr/include/stdlib.h:773:14: note: previous declaration of ‘getenv’ with type ‘char *(const char *)’
  773 | extern char *getenv (const char *__name) __THROW __nonnull ((1)) __wur;
      |              ^~~~~~
make: *** [<builtin>: input.o] Error 1
```

I think this error is reproducible

Regards from France

Basile STARYNKEVITCH           <basile@starynkevitch.net>
8 rue de la Faïencerie
92340 Bourg-la-Reine,          France
http://starynkevitch.net/Basile & https://github.com/bstarynk 
https://github.com/RefPerSys/RefPerSys/

**Comment by bstarynk** [comment]
This bug has been corrected in es from git, its commit e2ebbffcd281b4

**Comment by jpco** [comment]
IIRC, it was #106 which fixed this.  In any case, this is a good reason to release a 0.9.3 sooner rather than later.
